name = "autoflow"
main = "src/worker.js"
compatibility_date = "2024-03-25"

[assets]
directory = "public"  # 指向你的静态资源文件夹

[[kv_namespaces]]
binding = "CHECKIN_CONFIG"
id = "545e0894435d4feca26189c836822732"

[[kv_namespaces]]
binding = "AD_CONFIG"
id = "34b17f96cc20467eb4638a5015ea4f4f"

[[r2_buckets]]
binding = "APK_STORE"
bucket_name = "apk-store"

[vars]
CACHE_TTL = "60"  # 缓存1分钟
#CACHE_TTL = "3600"  # 缓存1小时
VERSION_CODE = "3"
VERSION_NAME = "0.3.0"
VERSION_DOWNLOAD_URL = "http://autoflow.xbdc.cn/download/app.apk"
VERSION_RELEASE_NOTES = "修复若干问题，提升稳定性。"
VERSION_FORCE_UPDATE = "false"
